AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Automatic enable flow logs"

Resources:
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - "lambda.amazonaws.com" 
                  Action: 
                    - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "create_flow_logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "ec2:CreateFlowLogs"
                Resource: "*"
        -
          PolicyName: "describe_logs"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "ec2:DescribeFlowLogs"
                Resource: "*"
              -
                Effect: "Allow"
                Action: "logs:DescribeLogGroups"
                Resource: "*"
        -
          PolicyName: "pass_role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "iam:PassRole"
                Resource: "*"
          
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "flow_logs_enable"
      Role: !GetAtt FunctionRole.Arn
      CodeUri: ./src
      Timeout: 20
      Handler: enable_flow_logs.lambda_handler
      Runtime: python3.6
    